//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEVotion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Style_Keyword_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Keyword_Color"]));
            }
            set {
                this["Style_Keyword_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Style_Keyword_Bold {
            get {
                return ((bool)(this["Style_Keyword_Bold"]));
            }
            set {
                this["Style_Keyword_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Keyword_Italic {
            get {
                return ((bool)(this["Style_Keyword_Italic"]));
            }
            set {
                this["Style_Keyword_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Style_Comment_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Comment_Color"]));
            }
            set {
                this["Style_Comment_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Comment_Bold {
            get {
                return ((bool)(this["Style_Comment_Bold"]));
            }
            set {
                this["Style_Comment_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Comment_Italic {
            get {
                return ((bool)(this["Style_Comment_Italic"]));
            }
            set {
                this["Style_Comment_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color Style_String_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_String_Color"]));
            }
            set {
                this["Style_String_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_String_Bold {
            get {
                return ((bool)(this["Style_String_Bold"]));
            }
            set {
                this["Style_String_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_String_Italic {
            get {
                return ((bool)(this["Style_String_Italic"]));
            }
            set {
                this["Style_String_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teal")]
        public global::System.Drawing.Color Style_Number_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Number_Color"]));
            }
            set {
                this["Style_Number_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Style_Number_Bold {
            get {
                return ((bool)(this["Style_Number_Bold"]));
            }
            set {
                this["Style_Number_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Number_Italic {
            get {
                return ((bool)(this["Style_Number_Italic"]));
            }
            set {
                this["Style_Number_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color Style_LoveKeyword_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_LoveKeyword_Color"]));
            }
            set {
                this["Style_LoveKeyword_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Style_LoveKeyword_Bold {
            get {
                return ((bool)(this["Style_LoveKeyword_Bold"]));
            }
            set {
                this["Style_LoveKeyword_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_LoveKeyword_Italic {
            get {
                return ((bool)(this["Style_LoveKeyword_Italic"]));
            }
            set {
                this["Style_LoveKeyword_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color Style_Constant_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Constant_Color"]));
            }
            set {
                this["Style_Constant_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Style_Constant_Bold {
            get {
                return ((bool)(this["Style_Constant_Bold"]));
            }
            set {
                this["Style_Constant_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Constant_Italic {
            get {
                return ((bool)(this["Style_Constant_Italic"]));
            }
            set {
                this["Style_Constant_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Style_Code_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Code_Color"]));
            }
            set {
                this["Style_Code_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Code_Bold {
            get {
                return ((bool)(this["Style_Code_Bold"]));
            }
            set {
                this["Style_Code_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Code_Italic {
            get {
                return ((bool)(this["Style_Code_Italic"]));
            }
            set {
                this["Style_Code_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Style_Scope_Color {
            get {
                return ((global::System.Drawing.Color)(this["Style_Scope_Color"]));
            }
            set {
                this["Style_Scope_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Style_Scope_Bold {
            get {
                return ((bool)(this["Style_Scope_Bold"]));
            }
            set {
                this["Style_Scope_Bold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Style_Scope_Italic {
            get {
                return ((bool)(this["Style_Scope_Italic"]));
            }
            set {
                this["Style_Scope_Italic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Path_Executable {
            get {
                return ((string)(this["Path_Executable"]));
            }
            set {
                this["Path_Executable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public global::System.Drawing.Color Style_Background {
            get {
                return ((global::System.Drawing.Color)(this["Style_Background"]));
            }
            set {
                this["Style_Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 9.75pt")]
        public global::System.Drawing.Font Style_Font {
            get {
                return ((global::System.Drawing.Font)(this["Style_Font"]));
            }
            set {
                this["Style_Font"] = value;
            }
        }
    }
}
